# Use root/example as user/password credentials
version: '3.1'

services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    environment:
      MONGO_HOST: "mongodb://db"
    ports:
      - "8080:80"
    links:
      - "mongo:db"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://db:27017/
    links:
      - "mongo:db"